(specifications->manifest '("python" "python-pytorch-cuda"
                            "python-torchvision-cuda"
                            "python-numpy"
                            "python-matplotlib"
                            "python-imageio"
                            "python-pytest"
                            "python-hypothesis"
                            "python-ruff"
                            "python-mypy"
                            "python-pydocstyle"))
