"""Utility functions for the EBM library."""

from .data import (
    AddNoise,
    BinaryTransform,
    DequantizeTransform,
    EnergyDataset,
    SyntheticDataset,
    compute_data_statistics,
    create_data_loaders,
    get_fashion_mnist_datasets,
    get_mnist_datasets,
)
from .initialization import (
    Initializer,
    InitMethod,
    calculate_gain,
    get_fan_in_and_fan_out,
    init_from_data_statistics,
    initialize_module,
    kaiming_init,
    normal_init,
    uniform_init,
    xavier_init,
)
from .tensor import (
    TensorStatistics,
    batch_mv,
    batch_outer_product,
    batch_quadratic_form,
    concat_tensors,
    create_causal_mask,
    create_padding_mask,
    ensure_tensor,
    expand_dims_like,
    log_sum_exp,
    masked_fill_inf,
    safe_log,
    safe_sqrt,
    shape_for_broadcast,
    split_tensor,
    stack_tensors,
)
from .visualization import (
    create_animation,
    plot_energy_histogram,
    plot_reconstruction_comparison,
    plot_training_curves,
    setup_style,
    tile_images,
    visualize_filters,
    visualize_samples,
)

__all__ = [
    "AddNoise",
    # Data utilities
    "BinaryTransform",
    "DequantizeTransform",
    "EnergyDataset",
    # Initialization
    "InitMethod",
    "Initializer",
    "SyntheticDataset",
    "TensorStatistics",
    "batch_mv",
    "batch_outer_product",
    "batch_quadratic_form",
    "calculate_gain",
    "compute_data_statistics",
    "concat_tensors",
    "create_animation",
    "create_causal_mask",
    "create_data_loaders",
    "create_padding_mask",
    # Tensor utilities
    "ensure_tensor",
    "expand_dims_like",
    "get_fan_in_and_fan_out",
    "get_fashion_mnist_datasets",
    "get_mnist_datasets",
    "init_from_data_statistics",
    "initialize_module",
    "kaiming_init",
    "log_sum_exp",
    "masked_fill_inf",
    "normal_init",
    "plot_energy_histogram",
    "plot_reconstruction_comparison",
    "plot_training_curves",
    "safe_log",
    "safe_sqrt",
    # Visualization
    "setup_style",
    "shape_for_broadcast",
    "split_tensor",
    "stack_tensors",
    "tile_images",
    "uniform_init",
    "visualize_filters",
    "visualize_samples",
    "xavier_init",
]
